import type { Metadata } from "next";
import {Roboto_Flex } from "next/font/google";
import LocalFont from "next/font/local";
import "./globals.css";

export const roboto = Roboto_Flex({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
})

const matter = LocalFont({
  src: './fonts/Matter-Light.ttf',
})

export const robotoItalic = LocalFont({
  src: './fonts/roboto-flex-latin.woff2',
})

export const matter400 = LocalFont({
  src: './fonts/Matter-Regular.ttf',
})

export const matter500 = LocalFont({
  src: './fonts/Matter-Medium.ttf',
})

export const matter700 = LocalFont({
  src: './fonts/Matter-Bold.ttf',
})


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${matter.className} antialiased overflow-x-hidden text-black`}
      >
        {children}
      </body>
    </html>
  );
}
